### ISSUE TITLE
bibtex instructions

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/lab-manual#7]
Add a comment and todo item about setting up the [CDL-bibliography](https://github.com/ContextLab/CDL-bibliography)

**Comment by paxtonfitzpatrick** [comment]
I think this is a bit beyond the TODO items for the on-boarding procedure.  We could add a walkthrough to the "Ask a question, answer a question" section, but:
1. It seems like we've generally moved towards adding the CDL-bibliography as a submodule for each project individually, rather than configuring the global LaTeX environment to use the main bibliography repo. 
2. The steps to set up the bibliography are already outlined pretty well in the [README](https://github.com/ContextLab/CDL-bibliography/blob/master/README.md), so it feels a bit redundant to take up space in the lab manual with them as well.

Going to close this for now, but feel free to re-open!
